open_ai_scene_types = {
    ("apartment",): "Apartment",
    ("bathroom",): "Bathroom",
    ("bedroom", "hotel"): "Bedroom / Hotel",
    ("hotel", "bedroom"): "Bedroom / Hotel",
    ("bookstore", "library"): "Bookstore / Library",
    ("library", "bookstore"): "Bookstore / Library",
    ("classroom",): "Classroom",
    ("conference", "room"): "Conference Room",
    ("copy", "mail", "room"): "Copy / Mail Room",
    ("mail", "copy", "room"): "Copy / Mail Room",
    ("kitchen",): "Kitchen",
    ("laundry",): "Laundry Room",
    ("living", "room", "lounge"): "Living room / Lounge",
    ("lounge", "living", "room"): "Living room / Lounge",
    ("lobby",): "Lobby",
    ("office",): "Office",
    ("storage", "basement", "garage"): "Storage / Basement / Garage",
    ("storage", "garage", "basement"): "Storage / Basement / Garage",
    ("basement", "storage", "garage"): "Storage / Basement / Garage",
    ("basement", "garage", "storage"): "Storage / Basement / Garage",
    ("garage", "storage", "basement"): "Storage / Basement / Garage",
    ("garage", "basement", "storage"): "Storage / Basement / Garage",
}
